name: Simple Build Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Also trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository's code

      - name: Build the project
        run: echo "Running build command"  # Replace with your actual build command, e.g., `make build`, `./build.sh`
